backend:
	name: git-gateway
	branch: master


media_folder: "assets/img"
public_folder: "img"

collections:
    -name: "coding"
      label: "Coding"
      folder: "assets"
      create: true
      slug: "{{year}}-{{slug}}"
      fields: 
          -{label: "Title", name:"title", widget: "string", required: true}